trigger:
  branches:
   include:
    - '*'
  tags:
   include:
    - '*'
  batch: 'true'
   

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Tailspin.SpaceGame.Web.csproj'